### PR TITLE
Fix bugs where invalid dates and times are still parsed

### LINKED ISSUE #159: [PE-D][Tester B] Appointment date mismatch
Although the success message says my appointment is on 31-02 the UI displays 28-02. I understand that Feb only has 28 days so you restricted it to that but I feel like it would be better to throw an error to let the user know he mistyped the date or else he may assume that everything is working fine.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Potatoad88/ped#8

### LINKED ISSUE #185: [PE-D][Tester B] Log date mismatch
Similar to appointment when I use the date 31-02 the UI displays 29-02. I understand that Feb only has 28 days so you restricted it to that but I feel like it would be better to throw an error to let the user know he mistyped the date or else he may assume that everything is working fine.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Potatoad88/ped#11

### LINKED ISSUE #190: [PE-D][Tester C] Appointment date edge case not handled properly
Setting appointment to 30/31 Feb will display as 29 Feb in UI

1. Enter: appt S1234567D a/30-02-2020 14:30
2. Invalid date does not cause error, instead executes successfully and shows up as 29th Feb in UI.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jeanyang04/ped#6

### PR DESCRIPTION
**Pull request by itsnotsherm**
fixes #185 fixes #190 fixes #159

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java [hunk 1]
```diff
@@ -29,90 +33,28 @@ public AppointmentCommand parse(String args) throws ParseException {
...
+        // Parse the date and time
+        String[] appointmentPrefixDate = argParts[1].split("app/");
+        if (appointmentPrefixDate.length != 2) {
+            throw new ParseException("Date and time provided are invalid.");
+        }
+        String appointmentDateTime = appointmentPrefixDate[1] + " " + argParts[2];
+        LocalDateTime dateTime;
+        try {
+            dateTime = LocalDateTime.parse(appointmentDateTime, DateTimeFormatter.ofPattern("dd-MM-uuuu HH:mm")
+                    .withResolverStyle(ResolverStyle.STRICT));
```
Comment (Dominic-Khoo) [inline src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java:55]: Nice! Using LocalDateTime leads to a much neater implementation.

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 2]
```diff
@@ -49,16 +49,17 @@ public LogCommand parse(String args) throws ParseException {
...
         // Parse the date and time
         String dateTimeString = argParts[1] + " " + argParts[2];
         LocalDateTime dateTime;
         try {
-            dateTime = LocalDateTime.parse(dateTimeString, DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
+            dateTime = LocalDateTime.parse(dateTimeString, DateTimeFormatter.ofPattern("dd-MM-uuuu HH:mm")
+                    .withResolverStyle(ResolverStyle.STRICT));
         } catch (Exception e) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, LogCommand.MESSAGE_USAGE));
+            throw new ParseException("Date and time provided are invalid.");
```
Comment (Dominic-Khoo) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:62]: More specific error messages is great so that the user understands what is wrong with their input

**Review by Dominic-Khoo — APPROVED** [review]
LGTM! This implementation should be less prone to bugs.
