### PR TITLE
bug fix - Command help messages do not work

### LINKED ISSUE #187: [PE-D][Tester C] Parameters for appointment is different from example
Parameter uses NRIC, however example uses index.

This leads to confusion on the correct command format.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jeanyang04/ped#5

### PR DESCRIPTION
**Pull request by volleyballkickedme**
close #187 #170 #194

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public AppointmentCommand parse(String args) throws ParseException {
 
         try {
             // Argument parts validation
-            dayString = argParts[1].substring(2, 12);
+            dayString = argParts[1].substring(4, 14);
```
Comment (Dominic-Khoo) [inline src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java:39]: Good catch

**Review by Dominic-Khoo — APPROVED** [review]

**Review by Dominic-Khoo — APPROVED** [review]
LGTM.
