### PR TITLE
Fix help window formatting

### LINKED ISSUE #89: Wrong formatting in Help page
image

Missing newline between add appointment and editing a person

### PR DESCRIPTION
**Pull request by reidenong**
fixes #89

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -26,7 +26,7 @@ public class HelpWindow extends UiPart<Stage> {
             + "<<Listing all persons>>\n"
             + "Format: list\n\n"
             + "<<Adding an appointment>>\n"
-            + "Format: appointment NRIC app/APPOINTMENT\n"
+            + "Format: appointment NRIC app/APPOINTMENT\n\n"
```
Comment (Dominic-Khoo) [inline src/main/java/seedu/address/ui/HelpWindow.java:29]: Good catch!

**Review by Dominic-Khoo — APPROVED** [review]
LGTM! Good catch for consistency in formatting
