### PR TITLE
Fix remark CLI message

### LINKED ISSUE #91: Add remark confusing CLI response
On doing add remark command, the CLI issues a response that exposes internals of AB3 and may be confusing for users

`
Added remark to Person: seedu.address.model.person.Person{name=John Doe, phone=98765432, email=johnd@example.com, nric=S1231231D, address=311, Clementi Ave 2, #02-25, remark=hello, tags=[[owesMoney], [friends]], appointment=null, logEntries=}
`

### PR DESCRIPTION
**Pull request by reidenong**
fixes #91

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RemarkCommand.java [hunk 1]
```diff
@@ -78,7 +78,7 @@ public CommandResult execute(Model model) throws CommandException {
      */
     private String generateSuccessMessage(Person personToEdit) {
         String message = !remark.value.isEmpty() ? MESSAGE_ADD_REMARK_SUCCESS : MESSAGE_DELETE_REMARK_SUCCESS;
-        return String.format(message, personToEdit);
+        return String.format(message, personToEdit.getName().toString());
```
Comment (Dominic-Khoo) [inline src/main/java/seedu/address/logic/commands/RemarkCommand.java:81]: LGTM! Should fix the bug that was mentioned.

**Review by Dominic-Khoo — APPROVED** [review]
LGTM!
